$env:DIARIO_BACKFILL_SECRET = "nexo-local-emulator-secret-dev"
$env:NEXO_USE_EMULATOR = "1"
$env:NEXT_PUBLIC_USE_EMULATOR = "1"
$env:FUNCTIONS_EMULATOR = "1"
$env:FIRESTORE_EMULATOR_HOST = "127.0.0.1:8080"
$env:FIREBASE_AUTH_EMULATOR_HOST = "127.0.0.1:9099"
$env:FIREBASE_STORAGE_EMULATOR_HOST = "127.0.0.1:9199"
Set-Location "$PSScriptRoot\.."
npm run dev *>> "$PSScriptRoot\..\logs\nexo-dev.log"
